### ISSUE TITLE
Quickstart: not having `virtualenv` installed results in broken DAGs

### ISSUE THREAD

**Issue by merobi-hub** [apache/airflow-site#945] opened 2024-01-30 04:03 UTC
Error-free installation of Airflow using the [Quickstart](https://airflow.apache.org/docs/apache-airflow/stable/start.html) seems to require `virtualenv`, but there is no mention of this in the guide.

The following example DAGs have the dependency:
- example_branch_operator_decorator
- example_branch_operator

<img width="1425" alt="Screenshot 2024-01-29 at 10 55 06 PM" src="https://github.com/apache/airflow-site/assets/68482867/4927d6df-c505-4602-ac74-95c205cea738">

**Comment by xionams** [comment] 2024-02-04 12:15
I dont think it is the best idea,
The Quickstart talked about how to "run" directly to airflow I dont know if this is a good idea to add it to Quickstart just for those two examples only, it's like adding it as a dependency while installing the package but using it just in two examples, I think add it to quickstart as a note or add it as dependency is just the same
maybe the better idea is to add it to the specific example docstring

**Comment by potiuk** [comment] 2024-02-05 15:26
The problem is that those examples are there, and they will fail to import resulting in red nasty errors as you see when you enable exampes. That's a bad first-encounter with Airflow and you will look for errorrs. 

Better solution indeed could be to not fail those examples i.e. add conditional code that will skip DAG creation from examples when virtualenv is not available. That would be the best option.

**Comment by xionams** [comment] 2024-02-05 18:28
> The problem is that those examples are there, and they will fail to import resulting in red nasty errors as you see when you enable exampes. That's a bad first-encounter with Airflow and you will look for errorrs.
> 
> Better solution indeed could be to not fail those examples i.e. add conditional code that will skip DAG creation from examples when virtualenv is not available. That would be the best option.

@potiuk could you assign it to me? Thanks

**Comment by potiuk** [comment] 2024-02-05 19:13
assigned.

**Closed** 2024-02-23 19:04 UTC
Labels: good first issue
